# mise.toml - Development environment configuration for Haunt Junkies
# Install mise: https://mise.jdx.dev/getting-started.html
# Run: mise install

[tools]
node = "22.12.0"  # Node.js LTS version compatible with SvelteKit 6.x
# npm comes bundled with node

[env]
# Development environment variables
# Copy .env.example to .env and fill in your actual values
_.file = [".env"]

# Optional: Auto-install dependencies when entering directory
[tasks.install]
description = "Install project dependencies"
run = "npm install"

[tasks.dev]
description = "Start development server"
run = "npm run dev"
depends = ["install"]

[tasks.build]
description = "Build production bundle"
run = "npm run build"
depends = ["install"]

[tasks.preview]
description = "Preview production build"
run = "npm run preview"
depends = ["build"]

[tasks.check]
description = "Run type checking"
run = "npm run check"
depends = ["install"]

[tasks.format]
description = "Format code with Prettier"
run = "npx prettier --write ."
depends = ["install"]

[tasks.lint]
description = "Lint code"
run = "npm run lint"
depends = ["install"]

# Project settings
[settings]
experimental = true
